version: "3"

services:
  django:
    build:
      context: .
    container_name: django
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py makesuper &&
              python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    volumes:
        - .:/usr/src/app
    ports:
        - "8000:8000"
    depends_on:
        - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
    - POSTGRES_DB=postgres
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres